engine:
  tickTargetPerSec: 60
  spriteAnimationFramePerSec: 12
viewport:
  x: 0
  y: 768
  width: 1024
  height: 768
player:
  asset:
    path: "https://sparrow-assets.pages.dev/sparrow-comp.png"
  width: 128
  height: 128
  x: 0
  y: 1350
global:
    splash:
        asset:
            path: "https://sparrow-assets.pages.dev/splash.png"
            width: 1024
            height: 768
    ending:
        asset:
            path: "https://sparrow-assets.pages.dev/ending.png"
            width: 1024
            height: 768
map:
  width: 2048
  height: 1536
  bg: "https://sparrow-assets.pages.dev/map1-bg-full-comp.png"
  mg: "https://sparrow-assets.pages.dev/map1-mg-full-comp.png"
  fg: "https://sparrow-assets.pages.dev/map1-fg-full-comp.png"
  col: "https://sparrow-assets.pages.dev/map1-collision.png"
  collision:
    visible: true
  itemDots:
    visible: true
  item:
    asset:
      one:
        width: 64
        height: 64
        path: "https://sparrow-assets.pages.dev/greenie-full.png"
      two:
        width: 64
        height: 64
        path: "https://sparrow-assets.pages.dev/finish-item.png"
    position:
      # noinspection SpringBootApplicationYaml
      0:
        x: 0
        y: 450
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      1:
        x: 170
        y: 192
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      2:
        x: 597
        y: 192
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      3:
        x: 1024
        y: 192
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      4:
        x: 1451
        y: 192
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      5:
        x: 1878
        y: 192
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      6:
        x: 170
        y: 512
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      7:
        x: 597
        y: 512
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      8:
        x: 1024
        y: 512
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      9:
        x: 1451
        y: 512
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      10:
        x: 1878
        y: 512
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      11:
        x: 170
        y: 832
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      12:
        x: 597
        y: 832
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      13:
        x: 1024
        y: 832
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      14:
        x: 1451
        y: 832
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      15:
        x: 1878
        y: 832
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      16:
        x: 170
        y: 1152
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      17:
        x: 597
        y: 1152
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      18:
        x: 1024
        y: 1152
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      19:
        x: 1451
        y: 1152
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      20:
        x: 1878
        y: 1152
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      21:
        x: 170
        y: 1344
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      22:
        x: 597
        y: 1344
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      23:
        x: 1024
        y: 1344
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      24:
        x: 1451
        y: 1344
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      25:
        x: 1878
        y: 1344
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      26:
        x: 170
        y: 1472
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      27:
        x: 597
        y: 1472
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      28:
        x: 1024
        y: 1472
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      29:
        x: 1451
        y: 1472
        type: "collectable"
        ref: "one"
      30:
          x: 797
          y: 450
          type: "finish"
          ref: "two"
  enemy:
    asset:
      one:
        width: 128
        height: 128
        path: "https://sparrow-assets.pages.dev/vacuum.png"
      two:
        width: 128
        height: 64
        path: "https://sparrow-assets.pages.dev/deebot-full.png"
    position:
      # noinspection SpringBootApplicationYaml
      0:
        x: 1600
        y: 450
        type: "blocker"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      1:
        x: 1500
        y: 224
        type: "shooter"
        ref: "two"
      # noinspection SpringBootApplicationYaml
      2:
        x: 500
        y: 672
        type: "runner"
        ref: "two"
  directive:
    initial:
      text: "Collect all the greenies!"
      color: "black"
    finish:
      text: "Find the golden greenie!"
      color: "red"
    complete:
      text: "You won!"
      color: "blue"


particle:
  player:
    movement:
      # noinspection SpringBootApplicationYaml
      color:
        r: 230
        g: 234
        b: 218
        a: 255
    collision:
      # noinspection SpringBootApplicationYaml
      color:
        r: 255
        g: 255
        b: 255
        a: 255
  enemy:
    projectile:
      # noinspection SpringBootApplicationYaml
      color:
        r: 255
        g: 255
        b: 255
        a: 255
audio:
  player:
    jump: "https://sparrow-assets.pages.dev/jump-sound.wav"
    collision: "https://sparrow-assets.pages.dev/player-collision.wav"
  item:
    collect: "https://sparrow-assets.pages.dev/item-collect.wav"
  background: "https://sparrow-assets.pages.dev/level-1-music.wav"
  enemy:
    shoot: "https://sparrow-assets.pages.dev/shoot.wav"
